field: be24e339-2a08-4215-9bc0-241ebc74116d # Column 1 Support Items
fieldLayouts:
  e6c87515-3ebb-486f-b6d9-cadde5bb44b6:
    tabs:
      -
        elements:
          -
            fieldUid: 6ba35fc6-e896-4324-9c91-1cf1c22f713b # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 957dd092-8db9-463b-ad92-24583f950d83 # Details
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6ba35fc6-e896-4324-9c91-1cf1c22f713b: # Title
    columnSuffix: npoodumh
    contentColumnType: text
    fieldGroup: null
    handle: supportTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  957dd092-8db9-463b-ad92-24583f950d83: # Details
    columnSuffix: esshfitf
    contentColumnType: text
    fieldGroup: null
    handle: supportDetails
    instructions: ''
    name: Details
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      defaultTransform: ''
      initJs: null
      purifierConfig: ''
      purifyHtml: '1'
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showUnpermittedFiles: ''
      showUnpermittedVolumes: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: supportItem
name: 'Support Item'
sortOrder: 1
