fieldLayouts:
  a1d5a2fe-187b-4dc4-82ff-28aef63cb010:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 6b717878-c25a-4644-b86d-59c6243d0cf1 # TItle - Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: df515d35-7e4e-4c9b-ac2e-698d9e31e566 # Title - Sub Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 6bf4edef-29d7-4b47-b188-a356cee054a3 # Heading Panel - Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 18b9864d-5ec0-40a3-bb5e-9904ea978590 # Heading Panel - Main
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: f46c61bf-4fa8-4cfd-8d9f-c28351d2d027 # Tier 1 - Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 278351f1-b7df-45bb-b096-97130c8d18a3 # Tier 1 - Cost
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: ad166849-481c-4289-8a18-fec453f14678 # Tier 1 - Logs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: cd85cc9b-42c0-49c3-a746-2d0b2a2a3b9c # Tier 1 - Signup URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 36a0ba59-7e39-47d9-9f38-a628c5d28169 # Tier 2 - Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 292520de-da38-4ad3-afe5-5a7780de0935 # Tier 2 - Cost
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 29a018c1-a44e-4ff1-930d-5f2fc1bf4bb4 # Tier 2 - Logs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: b5799cfd-2e2e-4387-be35-f4d71cf06a5a # Tier 2 - Signup URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 7b549367-5368-4b82-94e1-7c62a35da98b # Tier 3 - Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 7beafeb4-a098-4122-8e7f-dae385f894e7 # Tier 3 - Cost
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 6caebce6-b832-4d92-8e56-2e1a41587390 # Tier 3 - Logs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: bcdec288-310d-414b-8e44-9ddd89e13506 # Tier 3 - Signup URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: b4a62d6a-9854-4f31-a331-d88f4d72d2cb # Tier 4 - Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 24f168b0-5e1a-4d3a-9b99-3f94dd8af984 # Tier 4 - Cost
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 475c7d20-53e5-4a28-bb13-dacdd70a98d9 # Tier 4 - Logs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 8127efd5-7682-4cc2-b312-6b82430affb0 # Tier 4 - Signup URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 8155be39-aad4-4f27-b16d-ab1284b07032 # Tier 5 - Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 033a118f-36aa-4135-bac3-af99f2dd3f0e # Tier 5 - Cost
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 97cf6e3a-caca-403e-b851-3504080ab780 # Tier 5 - Logs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 26c377ab-0107-4eb6-ab87-238eb627ccfc # Tier 5 - Signup URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: b7e2b9f6-243c-4083-a526-692e42b9ae75 # Features
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 31bd9fcc-48e0-4999-98a7-84d9f8ddbd76 # Start Using - Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bc7eef3d-d44f-4f82-a03b-8219fd5b6841 # Start Using - Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: beb03a16-866e-431e-9c85-b4c2e18b71a0 # Start Using - Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 259bc339-33c6-4a18-9d90-a6c734ada120 # Start Using Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 5ac68e79-c2ea-4acb-aae5-13d580fa68c3 # FAQs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: pricing
hasTitleField: false
name: Pricing
section: 3a7887b3-e2e7-4af8-9752-150a631a3995 # Pricing
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
