columnSuffix: tcicmcov
contentColumnType: string
fieldGroup: 9cfb0a89-3d38-4089-8a83-e5fccee758d4 # Globals
handle: email
instructions: ''
name: Email
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
