columnSuffix: aldgmsel
contentColumnType: text
fieldGroup: bcbfd88c-f1ba-406c-9e6a-a8def1440bb9 # Common
handle: headingPanelMain
instructions: ''
name: 'Heading Panel - Main'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  defaultTransform: ''
  initJs: null
  purifierConfig: ''
  purifyHtml: '1'
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
