columnSuffix: kwktdsoc
contentColumnType: text
fieldGroup: a1aca50b-c7fd-46a4-86d1-8404bd6a4327 # Home
handle: howItWorksDescription
instructions: ''
name: 'How it Works - Description'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  defaultTransform: ''
  initJs: null
  purifierConfig: ''
  purifyHtml: '1'
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
