columnSuffix: null
contentColumnType: string
fieldGroup: a1aca50b-c7fd-46a4-86d1-8404bd6a4327 # Home
handle: howItWorksCollage
instructions: ''
name: 'How It Works - Collage'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:2a8ddfe2-e7fd-4013-98d7-ad972f3eab5d' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:2a8ddfe2-e7fd-4013-98d7-ad972f3eab5d' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
