columnSuffix: aglthhje
contentColumnType: text
fieldGroup: a1aca50b-c7fd-46a4-86d1-8404bd6a4327 # Home
handle: howItWorksTextLink
instructions: ''
name: 'How it Works - Text Link'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Link Text'
            -
              - handle
              - linkText
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Link URL'
            -
              - handle
              - linkUrl
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
