columnSuffix: null
contentColumnType: string
fieldGroup: a1aca50b-c7fd-46a4-86d1-8404bd6a4327 # Home
handle: sliderTiles
instructions: ''
name: 'Slider - Tiles'
searchable: false
settings:
  contentTable: '{{%matrixcontent_slidertiles}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
