columnSuffix: null
contentColumnType: string
fieldGroup: a31a95a6-5d0a-4094-987e-bc936c432380 # Features
handle: solutions
instructions: ''
name: Solutions
searchable: false
settings:
  contentTable: '{{%matrixcontent_solutions}}'
  maxBlocks: '5'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
