columnSuffix: shgdamvw
contentColumnType: text
fieldGroup: a31a95a6-5d0a-4094-987e-bc936c432380 # Features
handle: solutionsIntro
instructions: ''
name: 'Solutions Intro'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  defaultTransform: ''
  initJs: null
  purifierConfig: ''
  purifyHtml: '1'
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
